Improves CI

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -9,28 +9,214 @@ on:
 jobs:
   build:
     runs-on: ubuntu-latest
+
     steps:
     - name: Checkout
-      uses: actions/checkout@v2
-
-    - name: Install node
-      uses: actions/setup-node@v1
+      uses: actions/checkout@v3
+    
+    # Use mamba instead due to freecad
+    #- name: Base Setup
+    #  uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
+    #- name: Install dependencies
+    #  run: python -m pip install -U jupyterlab>=0.4.0a32
+    
+    - name: Install Conda environment with Micromamba
+      uses: mamba-org/provision-with-micromamba@main
       with:
-       node-version: '14.x'
+        environment-name: cad
+        environment-file: false
+        channels: conda-forge/label/jupyterlab_alpha,conda-forge
+        extra-specs: |
+          python=3.9
+          nodejs=16
+          yarn
+          jupyterlab=4.0.0a32
+          freecad
+
+    - name: Lint the extension
+      shell: bash -l {0}
+      run: |
+        set -eux
+        jlpm
+        jlpm run lint:check
+
+    # We don't have tests
+    #- name: Test the extension
+    #  shell: bash -l {0}
+    #  run: |
+    #    set -eux
+    #    jlpm run test
+    
+    - name: Build the extension
+      shell: bash -l {0}
+      run: |
+        set -eux
+        python -m pip install .
+
+        jupyter labextension list
+        jupyter labextension list 2>&1 | grep -ie "jupytercad.*OK"
+        python -m jupyterlab.browser_check
+
+    - name: Package the extension
+      shell: bash -l {0}
+      run: |
+        set -eux
+        pip install build
+        python -m build
+        pip uninstall -y "jupytercad" jupyterlab
+
+    - name: Upload extension packages
+      uses: actions/upload-artifact@v3
+      with:
+        name: extension-artifacts
+        path: dist/jupytercad*
+        if-no-files-found: error
+
+  test_isolated:
+    needs: build
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v3
 
     - name: Install Python
-      uses: actions/setup-python@v2
+      uses: actions/setup-python@v4
       with:
-        python-version: '3.8'
+        python-version: '3.9'
         architecture: 'x64'
+    
+    - uses: actions/download-artifact@v3
+      with:
+        name: extension-artifacts
+
+    - name: Install and Test
+      run: |
+        set -eux
+        # Remove NodeJS, twice to take care of system and locally installed node versions.
+        sudo rm -rf $(which node)
+        sudo rm -rf $(which node)
+        pip install "jupyterlab>=4.0.0a32" jupytercad*.whl
+
+        jupyter labextension list
+        jupyter labextension list 2>&1 | grep -ie "jupytercad.*OK"
+        # jupyterlab.browser_check will fail due to the core extension jupyterlab_pygments.
+        # It does not support lab v4.0.0
+        #python -m jupyterlab.browser_check --no-chrome-test
+
+  integration-tests:
+    name: Integration tests
+    needs: build
+    runs-on: ubuntu-latest
+
+    env:
+      PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/pw-browsers
+
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v3
+
+    # Use mamba instead due to freecad
+    #- name: Base Setup
+    #  uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
+    #- name: Install dependencies
+    #  run: python -m pip install -U jupyterlab>=0.4.0a32
+    
+    - name: Install Conda environment with Micromamba
+      uses: mamba-org/provision-with-micromamba@main
+      with:
+        environment-name: cad
+        environment-file: false
+        channels: conda-forge/label/jupyterlab_alpha,conda-forge
+        extra-specs: |
+          python=3.9
+          nodejs=16
+          yarn
+          jupyterlab=4.0.0a32
+          freecad
+
+    - name: Download extension package
+      uses: actions/download-artifact@v3
+      with:
+        name: extension-artifacts
+        
+    - name: Install the extension
+      shell: bash -l {0}
+      run: |
+        set -eux
+        python -m pip install jupytercad*.whl
+    
+    - name: Install dependencies
+      shell: bash -l {0}
+      working-directory: ui-tests
+      env:
+        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
+      run: jlpm install
+
+    - name: Set up browser cache
+      uses: actions/cache@v3
+      with:
+        path: |
+          ${{ github.workspace }}/pw-browsers
+        key: ${{ runner.os }}-${{ hashFiles('ui-tests/yarn.lock') }}
+
+    - name: Install browser
+      shell: bash -l {0}
+      run: jlpm playwright install chromium
+      working-directory: ui-tests
+
+    - name: Execute integration tests
+      shell: bash -l {0}
+      working-directory: ui-tests
+      run: |
+        jlpm playwright test
+    
+    - name: Upload Playwright Test report
+      if: always()
+      uses: actions/upload-artifact@v3
+      with:
+        name: jupytercad-playwright-tests
+        path: |
+          ui-tests/test-results
+          ui-tests/playwright-report
+  
+  check_links:
+    name: Check Links
+    runs-on: ubuntu-latest
+    timeout-minutes: 15
+    steps:
+      - uses: actions/checkout@v3
+      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
+      - uses: jupyterlab/maintainer-tools/.github/actions/check-links@v1
+  
+  build_opencascade:
+    name: Build Opencascade
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v3
+    
+    - name: Install Conda environment with Micromamba
+      uses: mamba-org/provision-with-micromamba@main
+      with:
+        environment-name: cad
+        environment-file: false
+        channels: conda-forge/label/jupyterlab_alpha,conda-forge
+        extra-specs: |
+          python=3.9
+          nodejs=16
+          yarn
+          jupyterlab=4.0.0a32
+          freecad
 
     - name: Setup pip cache
       uses: actions/cache@v2
       with:
         path: ~/.cache/pip
-        key: pip-3.8-${{ hashFiles('package.json') }}
+        key: pip-3.9-${{ hashFiles('package.json') }}
         restore-keys: |
-          pip-3.8-
+          pip-3.9-
           pip-
 
     - name: Get yarn cache directory path
@@ -56,10 +242,8 @@ jobs:
           jupytercad-opencascade/lib/jupytercad.opencascade.version
         key: ${{ hashFiles('jupytercad-opencascade/build.yml') }}
 
-    - name: Install dependencies
-      run: python -m pip install -U "jupyterlab>=4.0.0a32"
-
     - name: Build jupytercad-opencascade
+      shell: bash -l {0}
       run: |
         jlpm
         jlpm run build
@@ -67,6 +251,7 @@ jobs:
       working-directory: jupytercad-opencascade
 
     - name: Build the extension
+      shell: bash -l {0}
       run: |
         jlpm link jupytercad-opencascade
 
@@ -85,103 +270,3 @@ jobs:
         cp dist/*.whl .
         pip uninstall -y "jupytercad" jupyterlab
         rm -rf myextension
-
-    - uses: actions/upload-artifact@v2
-      with:
-        name: myextension-whl
-        path: "*.whl"
-
-  test_integration:
-    name: Integration tests
-    needs: build
-    runs-on: ubuntu-latest
-    env:
-      PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/pw-browsers
-
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v3
-
-    - name: Setup mamba
-      uses: conda-incubator/setup-miniconda@v2
-      with:
-        miniforge-variant: Mambaforge
-        miniforge-version: latest
-
-    - name: Create the conda environment
-      shell: bash -l {0}
-      run: mamba install -q python=3.9 pip freecad
-
-    - name: Download extension package
-      uses: actions/download-artifact@v3
-      with:
-        name: myextension-whl
-
-    - name: Install the extension
-      shell: bash -l {0}
-      run: |
-        whereis python
-        python -m pip install --find-links=. jupytercad
-        python -m pip install "jupyterlab>=4.0.0a32"
-
-    - name: Install dependencies
-      shell: bash -l {0}
-      working-directory: ui-tests
-      env:
-        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
-      run: jlpm install
-
-    - name: Set up browser cache
-      uses: actions/cache@v3
-      with:
-        path: |
-          ${{ github.workspace }}/pw-browsers
-        key: ${{ runner.os }}-${{ hashFiles('ui-tests/yarn.lock') }}
-
-    - name: Install browser
-      shell: bash -l {0}
-      run: jlpm playwright install chromium
-      working-directory: ui-tests
-
-    - name: Execute integration tests
-      shell: bash -l {0}
-      working-directory: ui-tests
-      run: |
-        jlpm playwright test
-
-    - name: Upload Playwright Test report
-      if: always()
-      uses: actions/upload-artifact@v3
-      with:
-        name: jupytercad-playwright-tests
-        path: |
-          ui-tests/test-results
-          ui-tests/playwright-report
-
-  test_isolated:
-    needs: build
-    runs-on: ubuntu-latest
-
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v2
-
-    - name: Install Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: '3.8'
-        architecture: 'x64'
-
-    - uses: actions/download-artifact@v2
-      with:
-        name: myextension-whl
-
-    - name: Install and Test
-      run: |
-        set -eux
-        # Remove NodeJS, twice to take care of system and locally installed node versions.
-        sudo rm -rf $(which node)
-        sudo rm -rf $(which node)
-        pip install --find-links=. jupytercad
-        pip install "jupyterlab>=4.0.0a32"
-        jupyter labextension list 2>&1 | grep -ie "jupytercad.*OK"
